import { PrismaClient } from '@prisma/client';
import * as dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

const books = [
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publishedYear: 1960,
    genre: "Fiction",
    isbn: "9780061120084",
    available: true,
    image: "https://example.com/images/to-kill-a-mockingbird.jpg",
    lender: "John Doe",
  },
  {
    title: "1984",
    author: "George Orwell",
    publishedYear: 1949,
    genre: "Dystopian",
    isbn: "9780451524935",
    available: false,
    image: "https://example.com/images/1984.jpg",
    lender: "Jane Smith",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publishedYear: 1925,
    genre: "Classic",
    isbn: "9780743273565",
    available: true,
    image: "https://example.com/images/the-great-gatsby.jpg",
    lender: "Alice Johnson",
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publishedYear: 1813,
    genre: "Romance",
    isbn: "9781503290563",
    available: true,
    image: "https://example.com/images/pride-and-prejudice.jpg",
    lender: "Bob Brown",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publishedYear: 1951,
    genre: "Fiction",
    isbn: "9780316769488",
    available: false,
    image: "https://example.com/images/the-catcher-in-the-rye.jpg",
    lender: "Mary Davis",
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishedYear: 1937,
    genre: "Fantasy",
    isbn: "9780547928227",
    available: true,
    image: "https://example.com/images/the-hobbit.jpg",
    lender: "Unknown",
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    publishedYear: 1851,
    genre: "Adventure",
    isbn: "9781503280786",
    available: true,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "Unknown",
  },
  {
    title: "War and Peace",
    author: "Leo Tolstoy",
    publishedYear: 1869,
    genre: "Historical",
    isbn: "9781400079988",
    available: false,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "Kevin Wilson",
  },
  {
    title: "The Odyssey",
    author: "Homer",
    publishedYear: -800,
    genre: "Epic",
    isbn: "9780140268867",
    available: true,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "Laura Martinez",
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    publishedYear: 1866,
    genre: "Psychological Fiction",
    isbn: "9780486415871",
    available: true,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "David Lee",
  },
  {
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    publishedYear: 1847,
    genre: "Romance",
    isbn: "9780141441146",
    available: true,
    image: "https://example.com/images/jane-eyre.jpg",
    lender: "Unknown",
  },
  {
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    publishedYear: 1320,
    genre: "Epic Poetry",
    isbn: "9780142437223",
    available: false,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "Emma Taylor",
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    publishedYear: 1932,
    genre: "Dystopian",
    isbn: "9780060850524",
    available: true,
    image: "https://example.com/images/brave-new-world.jpg",
    lender: "Unknown",
  },
  {
    title: "The Iliad",
    author: "Homer",
    publishedYear: -750,
    genre: "Epic",
    isbn: "9780140275360",
    available: true,
    image: "https://example.com/images/the-iliad.jpg",
    lender: "Unknown",
  },
  {
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    publishedYear: 1880,
    genre: "Philosophical Fiction",
    isbn: "9780374528379",
    available: true,
    image: "https://example.com/images/the-brothers-karamazov.jpg",
    lender: "Unknown",
  },
  {
    title: "Wuthering Heights",
    author: "Emily Brontë",
    publishedYear: 1847,
    genre: "Gothic Fiction",
    isbn: "9780141439556",
    available: false,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "Sophia Anderson",
  },
  {
    title: "Les Misérables",
    author: "Victor Hugo",
    publishedYear: 1862,
    genre: "Historical",
    isbn: "9780451419438",
    available: true,
    image: "https://example.com/images/les-miserables.jpg",
    lender: "Unknown",
  },
  {
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    publishedYear: 1615,
    genre: "Adventure",
    isbn: "9780060934347",
    available: true,
    image: "https://example.com/images/don-quixote.jpg",
    lender: "Unknown",
  },
  {
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    publishedYear: 1857,
    genre: "Literary Fiction",
    isbn: "9780140449129",
    available: false,
    image: "https://example.com/images/moby-dick.jpg",
    lender: "James Thomas",
  },
  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    publishedYear: 1890,
    genre: "Philosophical Fiction",
    isbn: "9780141439570",
    available: true,
    image: "https://example.com/images/the-picture-of-dorian-gray.jpg",
    lender: "Unknown",
  },
];
async function main() {
  try {
    for (const book of books) {
      await prisma.book.create({
        data: book,
      });
    }
    console.log("Seeding completed successfully.");
  } catch (e) {
    console.error("Error during seeding:", e);
  } finally {
    await prisma.$disconnect();
  }
}

main();